#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to install and configure Nginx

# Update package list and install nginx
apt-get update -y
apt-get install nginx -y

# Ensure Nginx is configured to listen on port 80
# This is usually the default, but let's make sure

# Create a simple HTML page with "Holberton School"
echo "Holberton School for the win!" > /var/www/html/index.html

# Restart nginx service (without using systemctl)
service nginx restart
