#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to install and configure Nginx

# Update package list and install nginx
apt-get update -y
apt-get install nginx -y

# Create a simple HTML page with "Holberton School"
echo "Holberton School for the win!" > /var/www/html/index.html

# Start nginx service (without using systemctl)
service nginx start
